using System;
using UnityEngine;
using UnityEngine.UI;
using UnityEditor;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Linq;

namespace CUiAutoBind
{
    /// <summary>
    /// 代码生成器，负责生成和更新 UI 绑定代码
    /// </summary>
    public class CodeGenerator
    {
        private BindConfig config;
        private HashSet<string> generatedPaths = new HashSet<string>();

        public CodeGenerator(BindConfig config)
        {
            this.config = config;
        }

        /// <summary>
        /// 生成代码
        /// </summary>
        public void GenerateCode(GameObject target, List<AutoBindData> bindings)
        {
            if (target == null || config == null)
            {
                Debug.LogError("GenerateCode: Target or Config is null");
                return;
            }

            if (!config.IsValid())
            {
                Debug.LogError("GenerateCode: Config is invalid");
                return;
            }

            // 重置状态
            generatedPaths.Clear();

            // 获取 AutoBind 组件
            AutoBind rootAutoBind = target.GetComponent<AutoBind>();
            if (rootAutoBind == null)
            {
                Debug.LogError("GenerateCode: Target GameObject does not have AutoBind component");
                return;
            }

            // 递归生成代码
            GenerateRecursiveCode(rootAutoBind);

            AssetDatabase.Refresh();
        }

        /// <summary>
        /// 递归生成代码
        /// </summary>
        private void GenerateRecursiveCode(AutoBind autoBind, string parentName = "")
        {
            // 获取这个 AutoBind 的自定义类名
            string className = autoBind.GetUIClassName();
            GameObject targetObj = autoBind.gameObject;

            // 生成当前对象的代码
            if (config.usePartialClass)
            {
                GenerateAutoFile(targetObj, autoBind, className, parentName);
                GenerateManualFile(targetObj, className, parentName);
            }
            else
            {
                GenerateSingleFile(targetObj, className, autoBind.GetValidBindings(), parentName);
            }

            // 递归生成子对象（默认总是生成所有子对象的代码）
            List<AutoBind> childAutoBinds = autoBind.GetChildAutoBinds();
            foreach (var childAutoBind in childAutoBinds)
            {
                // 当前对象的名称作为子对象的父名称
                GenerateRecursiveCode(childAutoBind, targetObj.name);
            }
        }

        /// <summary>
        /// 生成自动生成的部分文件（xxx.Auto.cs）
        /// </summary>
        private void GenerateAutoFile(GameObject target, AutoBind autoBind, string className, string parentName = "")
        {
            var bindings = autoBind.GetValidBindings();

            // 确定文件路径
            string filePath = GetFilePath(target.name, parentName, config.GetAutoGeneratedFilePath, $"{target.name}.Auto.cs");

            // 确保目录存在
            string directory = Path.GetDirectoryName(filePath);
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            // 获取子对象 AutoBind 列表及其类名
            // 只有在 bindings 中显式绑定了子对象时，才生成对应的字段
            List<AutoBind> childAutoBinds = autoBind.GetChildAutoBinds();
            List<ChildUIInfo> childUIInfos = new List<ChildUIInfo>();

            foreach (var childAutoBind in childAutoBinds)
            {
                // 检查是否在 bindings 中显式绑定了这个子对象
                bool isExplicitlyBound = bindings.Exists(b =>
                    b.IsAutoBindReference() &&
                    b.component == childAutoBind &&
                    b.generateField);

                // 只有显式绑定的子对象才生成字段
                if (isExplicitlyBound)
                {
                    string childClassName = childAutoBind.GetUIClassName();
                    string childFieldName = GetChildFieldName(childAutoBind);

                    childUIInfos.Add(new ChildUIInfo
                    {
                        className = childClassName,
                        fieldName = childFieldName
                    });
                }
            }

            // 生成代码内容
            string codeContent = GenerateAutoFileContent(className, bindings, childUIInfos, null);

            // 写入文件
            File.WriteAllText(filePath, codeContent, Encoding.UTF8);
            Debug.Log($"Auto file generated: {filePath}");
        }

        /// <summary>
        /// 获取文件路径（支持子对象）
        /// </summary>
        private string GetFilePath(string gameObjectName, string parentName, System.Func<string, string> basePathGetter, string fileName)
        {
            if (string.IsNullOrEmpty(parentName))
            {
                // 根对象：直接使用 GameObject 名称
                return basePathGetter(gameObjectName);
            }
            else
            {
                // 子对象：父对象目录 / 子对象名称
                string parentDir = Path.GetDirectoryName(basePathGetter(parentName));
                string childDir = Path.Combine(parentDir, gameObjectName);
                return Path.Combine(childDir, fileName);
            }
        }

        /// <summary>
        /// 获取子对象在父对象中的字段名
        /// </summary>
        private string GetChildFieldName(AutoBind childAutoBind)
        {
            // 查找包含此子对象 AutoBind 的父对象
            Transform current = childAutoBind.transform;
            AutoBind parentAutoBind = null;

            while (current != null && parentAutoBind == null)
            {
                current = current.parent;
                if (current != null)
                {
                    parentAutoBind = current.GetComponent<AutoBind>();
                }
            }

            // 在父对象的 bindings 中查找对应的绑定
            if (parentAutoBind != null)
            {
                var bindings = parentAutoBind.GetValidBindings();
                foreach (var binding in bindings)
                {
                    if (binding.IsAutoBindReference() && binding.component == childAutoBind)
                    {
                        return binding.fieldName;
                    }
                }
            }

            // 如果没有找到绑定，使用驼峰命名的 GameObject 名称
            string name = childAutoBind.gameObject.name;
            return char.ToLower(name[0]) + name.Substring(1);
        }

        /// <summary>
        /// 子对象 UI 信息
        /// </summary>
        private class ChildUIInfo
        {
            public string className;  // 子对象的 UI 类名（来自子对象的 customClassName）
            public string fieldName;  // 在父对象中的字段名
        }

        /// <summary>
        /// 生成手动文件（xxx.cs）
        /// </summary>
        private void GenerateManualFile(GameObject target, string className, string parentName = "")
        {
            string filePath = GetFilePath(target.name, parentName, config.GetManualFilePath, $"{target.name}.cs");

            // 确保目录存在
            string directory = Path.GetDirectoryName(filePath);
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            // 如果文件不存在，创建基本结构
            if (!File.Exists(filePath))
            {
                string codeContent = GenerateManualFileContent(className);
                File.WriteAllText(filePath, codeContent, Encoding.UTF8);
                Debug.Log($"Manual file created: {filePath}");
            }
        }

        /// <summary>
        /// 生成单个文件（旧模式，不使用 partial）
        /// </summary>
        private void GenerateSingleFile(GameObject target, string className, List<AutoBindData> bindings, string parentName = "")
        {
            string filePath = GetFilePath(target.name, parentName, config.GetGeneratedFilePath, $"{target.name}.cs");

            // 确保目录存在
            string directory = Path.GetDirectoryName(filePath);
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            // 生成代码内容
            string codeContent = GenerateSingleFileContent(className, bindings, filePath);

            // 写入文件
            File.WriteAllText(filePath, codeContent, Encoding.UTF8);
            Debug.Log($"Single file generated: {filePath}");
        }

        /// <summary>
        /// 生成自动文件的内容（xxx.Auto.cs）
        /// </summary>
        private string GenerateAutoFileContent(string className, List<AutoBindData> bindings, List<ChildUIInfo> childUIInfos, List<ChildUIInfo> allChildInfos = null)
        {
            StringBuilder sb = new StringBuilder();

            // 生成文件头
            GenerateFileHeader(sb, bindings);

            // 添加说明注释
            sb.AppendLine("// 自动生成的文件，请勿手动修改");
            sb.AppendLine("// 重新生成时会完全覆盖此文件");
            sb.AppendLine();

            // 生成命名空间
            if (!string.IsNullOrEmpty(config.namespaceName))
            {
                sb.AppendLine($"namespace {config.namespaceName}");
                sb.AppendLine("{");
            }

            // 生成类声明（使用 partial）
            sb.AppendLine($"    public partial class {className}{config.GetClassInheritance()}");
            sb.AppendLine("    {");

            // 生成字段（双文件模式不需要 region）
            GenerateFields(sb, bindings, allChildInfos);

            sb.AppendLine("    }");

            // 关闭命名空间
            if (!string.IsNullOrEmpty(config.namespaceName))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        /// <summary>
        /// 生成手动文件的内容（xxx.cs）
        /// </summary>
        private string GenerateManualFileContent(string className)
        {
            StringBuilder sb = new StringBuilder();

            // 生成文件头
            GenerateFileHeader(sb, new List<AutoBindData>());

            // 添加说明注释
            sb.AppendLine("// 手动编写的文件，可以自由修改");
            sb.AppendLine("// 重新生成自动文件时不会影响此文件");
            sb.AppendLine();

            // 生成命名空间
            if (!string.IsNullOrEmpty(config.namespaceName))
            {
                sb.AppendLine($"namespace {config.namespaceName}");
                sb.AppendLine("{");
            }

            // 生成类声明（使用 partial）
            sb.AppendLine($"    public partial class {className}{config.GetClassInheritance()}");
            sb.AppendLine("    {");
            sb.AppendLine("        // 在这里添加你的业务逻辑和方法");
            sb.AppendLine("    }");

            // 关闭命名空间
            if (!string.IsNullOrEmpty(config.namespaceName))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        /// <summary>
        /// 生成单个文件的内容（旧模式）
        /// </summary>
        private string GenerateSingleFileContent(string className, List<AutoBindData> bindings, string existingFilePath)
        {
            StringBuilder sb = new StringBuilder();

            // 生成文件头（传入 bindings 以自动收集命名空间）
            GenerateFileHeader(sb, bindings);

            // 生成命名空间
            if (!string.IsNullOrEmpty(config.namespaceName))
            {
                sb.AppendLine($"namespace {config.namespaceName}");
                sb.AppendLine("{");
            }

            // 解析现有的手动代码
            string manualCode = ParseExistingManualCode(existingFilePath);

            // 生成类声明
            GenerateClassDeclaration(sb, className);

            // 生成自动绑定区域
            sb.AppendLine($"    {BindConfig.AutoBindRegionStart}");
            GenerateFields(sb, bindings);
            sb.AppendLine($"    {BindConfig.AutoBindRegionEnd}");

            // 添加手动代码区域
            if (!string.IsNullOrEmpty(manualCode))
            {
                sb.AppendLine();
                sb.AppendLine($"    {BindConfig.ManualRegionStart}");
                sb.Append(manualCode);
                sb.AppendLine($"    {BindConfig.ManualRegionEnd}");
            }

            // 关闭类和命名空间
            sb.AppendLine("}");

            if (!string.IsNullOrEmpty(config.namespaceName))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        /// <summary>
        /// 生成文件头
        /// </summary>
        private void GenerateFileHeader(StringBuilder sb, List<AutoBindData> bindings)
        {
            sb.AppendLine("// Auto-generated by CUIBind");
            sb.AppendLine("// DO NOT EDIT MANUALLY IN THE AutoBind Generated REGION");
            sb.AppendLine();

            // 收集需要的命名空间
            HashSet<string> namespaces = new HashSet<string>();
            namespaces.Add("UnityEngine");
            namespaces.Add("UnityEngine.UI");

            // 添加生成的 UI 命名空间
            if (!string.IsNullOrEmpty(config.namespaceName))
            {
                namespaces.Add(config.namespaceName);
            }

            // 根据绑定组件类型添加命名空间
            foreach (var binding in bindings)
            {
                if (binding == null || binding.component == null)
                    continue;

                // AutoBind 绑定不需要额外命名空间（已添加 UI 命名空间）
                if (binding.IsAutoBindReference())
                    continue;

                Type componentType = binding.component.GetType();
                string ns = componentType.Namespace;

                if (!string.IsNullOrEmpty(ns))
                {
                    namespaces.Add(ns);
                }
            }

            // 添加额外的命名空间配置
            if (config.additionalNamespaces != null)
            {
                foreach (var ns in config.additionalNamespaces)
                {
                    if (!string.IsNullOrEmpty(ns))
                    {
                        namespaces.Add(ns);
                    }
                }
            }

            // 添加 using 语句
            foreach (var ns in namespaces.OrderBy(n => n))
            {
                sb.AppendLine($"using {ns};");
            }

            sb.AppendLine();
        }

        /// <summary>
        /// 生成类声明
        /// </summary>
        private void GenerateClassDeclaration(StringBuilder sb, string className)
        {
            string partialKeyword = config.usePartialClass ? "partial " : "";
            string inheritance = config.GetClassInheritance();
            sb.AppendLine($"    public {partialKeyword}class {className}{inheritance}");
            sb.AppendLine("    {");
        }

        /// <summary>
        /// 生成字段声明
        /// </summary>
        private void GenerateFields(StringBuilder sb, List<AutoBindData> bindings, List<ChildUIInfo> childInfos = null)
        {
            // 创建一个映射表，用于快速查找子对象信息
            Dictionary<string, string> childClassMap = new Dictionary<string, string>();
            if (childInfos != null)
            {
                foreach (var childInfo in childInfos)
                {
                    childClassMap[childInfo.fieldName] = childInfo.className;
                }
            }

            foreach (var binding in bindings)
            {
                if (binding == null || binding.component == null || !binding.generateField)
                    continue;

                string fieldName = binding.fieldName;

                // 检查是否是 AutoBind 绑定
                if (binding.IsAutoBindReference())
                {
                    AutoBind childAutoBind = binding.component as AutoBind;
                    if (childAutoBind != null)
                    {
                        string childClassName = childAutoBind.GetUIClassName();
                        // 添加 SerializeField 特性，以便在编辑器中赋值
                        sb.AppendLine($"        [SerializeField]");
                        sb.AppendLine($"        private {childClassName} {fieldName};");
                        sb.AppendLine();
                        continue;
                    }
                }

                // 普通组件绑定
                string componentTypeName = StringUtil.GetComponentTypeName(binding.ComponentType);

                // 普通组件也使用 SerializeField 并在编辑器中赋值
                sb.AppendLine($"        [SerializeField]");
                sb.AppendLine($"        private {componentTypeName} {fieldName};");
                sb.AppendLine();
            }
        }

        /// <summary>
        /// 解析现有的手动代码
        /// </summary>
        private string ParseExistingManualCode(string filePath)
        {
            if (!File.Exists(filePath))
                return null;

            string[] lines = File.ReadAllLines(filePath);
            List<string> manualCodeLines = new List<string>();
            bool inManualRegion = false;

            foreach (string line in lines)
            {
                if (line.Contains(BindConfig.ManualRegionStart))
                {
                    inManualRegion = true;
                    continue;
                }

                if (line.Contains(BindConfig.ManualRegionEnd))
                {
                    inManualRegion = false;
                    continue;
                }

                if (inManualRegion)
                {
                    manualCodeLines.Add(line);
                }
            }

            return manualCodeLines.Count > 0 ? string.Join("\n", manualCodeLines) : null;
        }
    }
}
